/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#2a6900',
        'primary-dim': '#235b00',
        'primary-container': '#84fb42',
        'primary-fixed': '#84fb42',
        'primary-fixed-dim': '#76ec33',
        'on-primary': '#d5ffb9',
        'on-primary-container': '#245c00',
        'on-primary-fixed': '#1a4700',
        'on-primary-fixed-variant': '#296700',
        'inverse-primary': '#84fb42',
        'secondary': '#00628c',
        'secondary-dim': '#00557a',
        'secondary-container': '#a3d8ff',
        'secondary-fixed': '#a3d8ff',
        'secondary-fixed-dim': '#80ccff',
        'on-secondary': '#e9f4ff',
        'on-secondary-container': '#004c6e',
        'on-secondary-fixed': '#003852',
        'on-secondary-fixed-variant': '#00567c',
        'tertiary': '#884d00',
        'tertiary-dim': '#774300',
        'tertiary-container': '#ff9810',
        'tertiary-fixed': '#ff9810',
        'tertiary-fixed-dim': '#ed8b00',
        'on-tertiary': '#fff0e5',
        'on-tertiary-container': '#4b2800',
        'on-tertiary-fixed': '#281300',
        'on-tertiary-fixed-variant': '#573000',
        'surface': '#f6f6f6',
        'surface-dim': '#d3d5d5',
        'surface-bright': '#f6f6f6',
        'surface-tint': '#2a6900',
        'surface-variant': '#dbdddd',
        'surface-container': '#e7e8e8',
        'surface-container-low': '#f0f1f1',
        'surface-container-high': '#e1e3e3',
        'surface-container-highest': '#dbdddd',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#2d2f2f',
        'on-surface-variant': '#5a5c5c',
        'background': '#f6f6f6',
        'on-background': '#2d2f2f',
        'outline': '#767777',
        'outline-variant': '#acadad',
        'inverse-surface': '#0c0f0f',
        'inverse-on-surface': '#9c9d9d',
        'error': '#b02500',
        'error-dim': '#b92902',
        'error-container': '#f95630',
        'on-error': '#ffefec',
        'on-error-container': '#520c00',
      },
      borderRadius: {
        DEFAULT: '1.25rem',
        lg: '2.5rem',
        xl: '4rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"ZCOOL KuaiLe"', '-apple-system', 'BlinkMacSystemFont', '"PingFang SC"', '"Hiragino Sans GB"', '"Microsoft YaHei"', '"Noto Sans SC"', '"Source Han Sans SC"', 'system-ui', 'sans-serif'],
        brush: ['"ZCOOL KuaiLe"', '-apple-system', 'BlinkMacSystemFont', '"PingFang SC"', '"Hiragino Sans GB"', '"Microsoft YaHei"', '"Noto Sans SC"', '"Source Han Sans SC"', 'system-ui', 'sans-serif'],
        body: ['-apple-system', 'BlinkMacSystemFont', '"PingFang SC"', '"Hiragino Sans GB"', '"Microsoft YaHei"', '"Noto Sans SC"', '"Source Han Sans SC"', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
